// Code generated by goctl. DO NOT EDIT.
package types

type FollowUserReq struct {
	FolloweeId int64 `json:"followeeId"`
}

type LikeAddReq struct {
	LikeType string `json:"likeType" validate:"required,regex=^(question|answer)$"`
	LikeId   int64  `json:"likeId"`
}
