// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	AnsOrCom "MouHu/service/app/qa/api/internal/handler/AnsOrCom"
	answer "MouHu/service/app/qa/api/internal/handler/answer"
	commit "MouHu/service/app/qa/api/internal/handler/commit"
	question "MouHu/service/app/qa/api/internal/handler/question"
	"MouHu/service/app/qa/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/question/publish",
					Handler: question.PubQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/question/list",
					Handler: question.GetQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/question/del",
					Handler: question.DelQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/question/alt",
					Handler: question.AltQuestionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/qa"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/answer/publish",
					Handler: answer.AnsQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/answer/list",
					Handler: answer.GetAnswerHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/qa"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/commit/publish",
					Handler: commit.ComAnswerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/commit/list",
					Handler: commit.GetCommitHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/qa"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/ansorcom/del",
					Handler: AnsOrCom.DelAnswerOrCommitHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/ansorcom/alt",
					Handler: AnsOrCom.AltAnswerOrCommitHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/qa"),
	)
}
