// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package server

import (
	"context"

	"MouHu/service/app/like/rpc/internal/logic"
	"MouHu/service/app/like/rpc/internal/svc"
	"MouHu/service/app/like/rpc/types/like"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	like.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) FollowUser(ctx context.Context, in *like.FollowUserReq) (*like.CommonResp, error) {
	l := logic.NewFollowUserLogic(ctx, s.svcCtx)
	return l.FollowUser(in)
}

func (s *LikeServer) LikeAdd(ctx context.Context, in *like.LikeAddReq) (*like.CommonResp, error) {
	l := logic.NewLikeAddLogic(ctx, s.svcCtx)
	return l.LikeAdd(in)
}
